import { createContext, useContext, useState, useEffect, type ReactNode } from "react";
import { SUPPORTED_LANGUAGES, type LanguageCode } from "@/components/booking/LanguageSelector";

interface LanguageContextType {
  language: LanguageCode;
  setLanguage: (lang: LanguageCode) => void;
  t: (key: string) => string;
}

const defaultContext: LanguageContextType = {
  language: "en",
  setLanguage: () => {},
  t: (key: string) => key,
};

const LanguageContext = createContext<LanguageContextType>(defaultContext);

const translations: Record<LanguageCode, Record<string, string>> = {
  en: {
    // Navbar
    home: "Home",
    accommodation: "Accommodation",
    rides: "Rides",
    event_halls: "Event Halls",
    how_it_works: "How It Works",
    for_providers: "For Providers",
    login: "Login",
    sign_up: "Sign Up",
    my_profile: "My Profile",
    favorites: "Favorites",
    my_bookings: "My Bookings",
    // Hero
    hero_badge: "Trusted by 50,000+ travelers",
    hero_title_1: "Discover Africa's",
    hero_title_2: "Hidden Gems",
    hero_subtitle: "Book accommodations, rides, and event halls seamlessly. Experience hassle-free travel across the continent via web or USSD.",
    stays: "Stays",
    events: "Events",
    location: "Location",
    check_in: "Check In",
    guests: "Guests",
    search: "Search",
    book_via_ussd: "Book via USSD:",
    how_it_works_link: "How it works",
    // Service Categories
    what_looking_for: "What Are You Looking For?",
    services_subtitle: "Explore our comprehensive services designed to make your African journey unforgettable.",
    accommodation_desc: "From luxury lodges to cozy guesthouses, find your perfect stay across Africa.",
    rides_transport: "Rides & Transport",
    rides_desc: "Safari vehicles, airport transfers, and city rides at your fingertips.",
    event_halls_title: "Event Halls",
    event_halls_desc: "Beautiful venues for weddings, conferences, and celebrations.",
    properties: "Properties",
    vehicles: "Vehicles",
    venues: "Venues",
    explore: "Explore",
    // Testimonials
    testimonials_title: "What Our Guests Say",
    testimonials_subtitle: "Don't just take our word for it. Here's what travelers across Africa have to say.",
    // CTA
    cta_badge: "For Service Providers",
    cta_title: "Grow Your Business with SafariStay",
    cta_subtitle: "Join thousands of property owners, vehicle operators, and event venue managers already earning with us.",
    become_partner: "Become a Partner",
    partner_login: "Partner Login",
    list_property: "List Your Property",
    list_property_desc: "Reach thousands of travelers across Africa",
    secure_payments: "Secure Payments",
    secure_payments_desc: "Get paid safely and on time, every time",
    support_24_7: "24/7 Support",
    support_24_7_desc: "Our team is always here to help you succeed",
    // Footer
    footer_desc: "Your trusted platform for accommodation, rides, and event venues across Africa. Experience seamless booking via web and USSD.",
    services: "Services",
    ussd_booking: "USSD Booking",
    company: "Company",
    about_us: "About Us",
    become_provider: "Become a Provider",
    careers: "Careers",
    support: "Support",
    help_center: "Help Center",
    contact_us: "Contact Us",
    privacy_policy: "Privacy Policy",
    terms_of_service: "Terms of Service",
    all_rights_reserved: "All rights reserved.",
    // FeaturedListings
    featured_stays: "Featured Stays",
    featured_stays_desc: "Handpicked accommodations offering exceptional experiences and value.",
    filter_all: "All",
    filter_lodges: "Lodges",
    filter_hotels: "Hotels",
    filter_villas: "Villas",
    filter_camps: "Camps",
    featured: "Featured",
    per_night: "/night",
    view_all_stays: "View All Stays",
    // HowItWorks
    how_it_works_badge: "Simple Process",
    how_it_works_title: "How It Works",
    how_it_works_subtitle: "From search to stay, we've made every step seamless — even without internet.",
    step_search: "Search & Discover",
    step_search_desc: "Browse curated listings of accommodations, rides, and event venues across Africa.",
    step_select: "Select & Customize",
    step_select_desc: "Choose your dates, guests, and any special requirements for your perfect stay.",
    step_book: "Book & Pay",
    step_book_desc: "Secure your reservation with mobile money, card, or USSD — whatever suits you.",
    step_enjoy: "Enjoy Your Stay",
    step_enjoy_desc: "Receive instant confirmation via SMS & voice call, then enjoy world-class hospitality.",
    step_ussd: "USSD Booking",
    step_ussd_desc: "No internet? Dial *384*123# from any phone to book — works on every network.",
  },
  sw: {
    home: "Nyumbani",
    accommodation: "Malazi",
    rides: "Usafiri",
    event_halls: "Kumbi za Hafla",
    how_it_works: "Jinsi Inavyofanya Kazi",
    for_providers: "Kwa Watoa Huduma",
    login: "Ingia",
    sign_up: "Jisajili",
    my_profile: "Wasifu Wangu",
    favorites: "Vipendwa",
    my_bookings: "Uhifadhi Wangu",
    hero_badge: "Kuaminiwa na wasafiri 50,000+",
    hero_title_1: "Gundua Afrika",
    hero_title_2: "Vito Vilivyofichwa",
    hero_subtitle: "Hifadhi malazi, usafiri, na kumbi za hafla kwa urahisi. Furahia usafiri usio na shida barani Afrika kupitia wavuti au USSD.",
    stays: "Malazi",
    events: "Hafla",
    location: "Mahali",
    check_in: "Kuingia",
    guests: "Wageni",
    search: "Tafuta",
    book_via_ussd: "Hifadhi kupitia USSD:",
    how_it_works_link: "Jinsi inavyofanya kazi",
    what_looking_for: "Unatafuta Nini?",
    services_subtitle: "Chunguza huduma zetu kamili zilizoundwa kufanya safari yako ya Afrika isiyosahaulika.",
    accommodation_desc: "Kutoka nyumba za kifahari hadi nyumba ndogo za wageni, pata makazi yako bora barani Afrika.",
    rides_transport: "Usafiri na Usafirishaji",
    rides_desc: "Magari ya safari, uhamisho wa uwanja wa ndege, na usafiri wa jijini mikononi mwako.",
    event_halls_title: "Kumbi za Hafla",
    event_halls_desc: "Maeneo mazuri kwa harusi, mikutano, na sherehe.",
    properties: "Mali",
    vehicles: "Magari",
    venues: "Maeneo",
    explore: "Chunguza",
    testimonials_title: "Wageni Wetu Wanasema Nini",
    testimonials_subtitle: "Usituchukue tu kwa neno letu. Hivi ndivyo wasafiri barani Afrika wanasema.",
    cta_badge: "Kwa Watoa Huduma",
    cta_title: "Kukuza Biashara Yako na SafariStay",
    cta_subtitle: "Jiunge na maelfu ya wamiliki wa mali, waendeshaji wa magari, na wasimamizi wa maeneo ya hafla ambao tayari wanapata.",
    become_partner: "Kuwa Mshirika",
    partner_login: "Kuingia kwa Mshirika",
    list_property: "Orodhesha Mali Yako",
    list_property_desc: "Fikia maelfu ya wasafiri barani Afrika",
    secure_payments: "Malipo Salama",
    secure_payments_desc: "Kulipwa kwa usalama na kwa wakati, kila wakati",
    support_24_7: "Msaada 24/7",
    support_24_7_desc: "Timu yetu iko hapa kila wakati kukusaidia kufanikiwa",
    footer_desc: "Jukwaa lako la kuaminika la malazi, usafiri, na maeneo ya hafla barani Afrika.",
    services: "Huduma",
    ussd_booking: "Uhifadhi wa USSD",
    company: "Kampuni",
    about_us: "Kuhusu Sisi",
    become_provider: "Kuwa Mtoa Huduma",
    careers: "Kazi",
    support: "Msaada",
    help_center: "Kituo cha Msaada",
    contact_us: "Wasiliana Nasi",
    privacy_policy: "Sera ya Faragha",
    terms_of_service: "Masharti ya Huduma",
    all_rights_reserved: "Haki zote zimehifadhiwa.",
    featured_stays: "Malazi Bora",
    featured_stays_desc: "Malazi yaliyochaguliwa kwa uangalifu yanayotoa uzoefu na thamani ya kipekee.",
    filter_all: "Yote",
    filter_lodges: "Nyumba za Wageni",
    filter_hotels: "Hoteli",
    filter_villas: "Villa",
    filter_camps: "Kambi",
    featured: "Bora",
    per_night: "/usiku",
    view_all_stays: "Ona Malazi Yote",
    how_it_works_badge: "Mchakato Rahisi",
    how_it_works_title: "Jinsi Inavyofanya Kazi",
    how_it_works_subtitle: "Kutoka utafutaji hadi kukaa, tumefanya kila hatua kuwa rahisi — hata bila intaneti.",
    step_search: "Tafuta na Gundua",
    step_search_desc: "Vinjari orodha za malazi, usafiri, na maeneo ya hafla barani Afrika.",
    step_select: "Chagua na Binafsisha",
    step_select_desc: "Chagua tarehe, wageni, na mahitaji yoyote maalum kwa kukaa kwako.",
    step_book: "Hifadhi na Lipa",
    step_book_desc: "Hifadhi nafasi yako kwa pesa za simu, kadi, au USSD.",
    step_enjoy: "Furahia Kukaa Kwako",
    step_enjoy_desc: "Pokea uthibitisho wa papo hapo kupitia SMS na simu, kisha furahia ukarimu.",
    step_ussd: "Uhifadhi wa USSD",
    step_ussd_desc: "Hakuna intaneti? Piga *384*123# kutoka simu yoyote kuhifadhi.",
  },
  fr: {
    home: "Accueil",
    accommodation: "Hébergement",
    rides: "Trajets",
    event_halls: "Salles d'événements",
    how_it_works: "Comment ça marche",
    for_providers: "Pour les prestataires",
    login: "Connexion",
    sign_up: "S'inscrire",
    my_profile: "Mon Profil",
    favorites: "Favoris",
    my_bookings: "Mes Réservations",
    hero_badge: "Approuvé par plus de 50 000 voyageurs",
    hero_title_1: "Découvrez l'Afrique",
    hero_title_2: "Trésors Cachés",
    hero_subtitle: "Réservez hébergements, trajets et salles d'événements en toute simplicité. Voyagez sans tracas via web ou USSD.",
    stays: "Séjours",
    events: "Événements",
    location: "Lieu",
    check_in: "Arrivée",
    guests: "Invités",
    search: "Rechercher",
    book_via_ussd: "Réserver via USSD :",
    how_it_works_link: "Comment ça marche",
    what_looking_for: "Que Cherchez-Vous ?",
    services_subtitle: "Explorez nos services complets conçus pour rendre votre voyage africain inoubliable.",
    accommodation_desc: "Des lodges de luxe aux maisons d'hôtes chaleureuses, trouvez votre séjour idéal en Afrique.",
    rides_transport: "Trajets & Transport",
    rides_desc: "Véhicules de safari, transferts aéroport et courses en ville à portée de main.",
    event_halls_title: "Salles d'Événements",
    event_halls_desc: "De beaux lieux pour mariages, conférences et célébrations.",
    properties: "Propriétés",
    vehicles: "Véhicules",
    venues: "Lieux",
    explore: "Explorer",
    testimonials_title: "Ce Que Disent Nos Clients",
    testimonials_subtitle: "Ne nous croyez pas sur parole. Voici ce que disent les voyageurs en Afrique.",
    cta_badge: "Pour les Prestataires",
    cta_title: "Développez Votre Activité avec SafariStay",
    cta_subtitle: "Rejoignez des milliers de propriétaires, opérateurs de véhicules et gestionnaires de salles déjà actifs.",
    become_partner: "Devenir Partenaire",
    partner_login: "Connexion Partenaire",
    list_property: "Listez Votre Propriété",
    list_property_desc: "Touchez des milliers de voyageurs à travers l'Afrique",
    secure_payments: "Paiements Sécurisés",
    secure_payments_desc: "Soyez payé en toute sécurité et à temps",
    support_24_7: "Support 24/7",
    support_24_7_desc: "Notre équipe est toujours là pour vous aider",
    footer_desc: "Votre plateforme de confiance pour l'hébergement, les trajets et les salles d'événements en Afrique.",
    services: "Services",
    ussd_booking: "Réservation USSD",
    company: "Entreprise",
    about_us: "À Propos",
    become_provider: "Devenir Prestataire",
    careers: "Carrières",
    support: "Support",
    help_center: "Centre d'Aide",
    contact_us: "Contactez-Nous",
    privacy_policy: "Politique de Confidentialité",
    terms_of_service: "Conditions d'Utilisation",
    all_rights_reserved: "Tous droits réservés.",
  },
  ar: {
    home: "الرئيسية",
    accommodation: "الإقامة",
    rides: "الرحلات",
    event_halls: "قاعات المناسبات",
    how_it_works: "كيف يعمل",
    for_providers: "لمقدمي الخدمات",
    login: "تسجيل الدخول",
    sign_up: "إنشاء حساب",
    my_profile: "ملفي الشخصي",
    favorites: "المفضلة",
    my_bookings: "حجوزاتي",
    hero_badge: "موثوق من قبل أكثر من 50,000 مسافر",
    hero_title_1: "اكتشف أفريقيا",
    hero_title_2: "الجواهر المخفية",
    hero_subtitle: "احجز أماكن الإقامة والرحلات وقاعات المناسبات بسهولة. استمتع بسفر خالٍ من المتاعب عبر الويب أو USSD.",
    stays: "الإقامات",
    events: "المناسبات",
    location: "الموقع",
    check_in: "تسجيل الوصول",
    guests: "الضيوف",
    search: "بحث",
    book_via_ussd: "احجز عبر USSD:",
    how_it_works_link: "كيف يعمل",
    what_looking_for: "ماذا تبحث عنه؟",
    services_subtitle: "استكشف خدماتنا الشاملة المصممة لجعل رحلتك الأفريقية لا تُنسى.",
    accommodation_desc: "من النزل الفاخرة إلى بيوت الضيافة المريحة، اعثر على إقامتك المثالية في أفريقيا.",
    rides_transport: "الرحلات والنقل",
    rides_desc: "مركبات السفاري ونقل المطار ورحلات المدينة في متناول يدك.",
    event_halls_title: "قاعات المناسبات",
    event_halls_desc: "أماكن جميلة للأعراس والمؤتمرات والاحتفالات.",
    properties: "عقارات",
    vehicles: "مركبات",
    venues: "أماكن",
    explore: "استكشف",
    testimonials_title: "ماذا يقول ضيوفنا",
    testimonials_subtitle: "لا تأخذ كلمتنا فقط. إليك ما يقوله المسافرون عبر أفريقيا.",
    cta_badge: "لمقدمي الخدمات",
    cta_title: "نمِّ عملك مع SafariStay",
    cta_subtitle: "انضم إلى آلاف مالكي العقارات ومشغلي المركبات ومديري قاعات الفعاليات.",
    become_partner: "كن شريكاً",
    partner_login: "دخول الشريك",
    list_property: "أدرج عقارك",
    list_property_desc: "اوصل لآلاف المسافرين عبر أفريقيا",
    secure_payments: "مدفوعات آمنة",
    secure_payments_desc: "احصل على أموالك بأمان وفي الوقت المحدد",
    support_24_7: "دعم على مدار الساعة",
    support_24_7_desc: "فريقنا دائماً هنا لمساعدتك على النجاح",
    footer_desc: "منصتك الموثوقة للإقامة والرحلات وقاعات المناسبات عبر أفريقيا.",
    services: "الخدمات",
    ussd_booking: "حجز USSD",
    company: "الشركة",
    about_us: "من نحن",
    become_provider: "كن مقدم خدمة",
    careers: "وظائف",
    support: "الدعم",
    help_center: "مركز المساعدة",
    contact_us: "اتصل بنا",
    privacy_policy: "سياسة الخصوصية",
    terms_of_service: "شروط الخدمة",
    all_rights_reserved: "جميع الحقوق محفوظة.",
  },
  pt: {
    home: "Início",
    accommodation: "Alojamento",
    rides: "Viagens",
    event_halls: "Salões de Eventos",
    how_it_works: "Como Funciona",
    for_providers: "Para Fornecedores",
    login: "Entrar",
    sign_up: "Registar",
    my_profile: "Meu Perfil",
    favorites: "Favoritos",
    my_bookings: "Minhas Reservas",
    hero_badge: "Confiável por mais de 50.000 viajantes",
    hero_title_1: "Descubra a África",
    hero_title_2: "Tesouros Escondidos",
    hero_subtitle: "Reserve alojamentos, viagens e salões de eventos sem complicações. Viaje sem stress via web ou USSD.",
    stays: "Estadas",
    events: "Eventos",
    location: "Localização",
    check_in: "Entrada",
    guests: "Hóspedes",
    search: "Pesquisar",
    book_via_ussd: "Reserve via USSD:",
    how_it_works_link: "Como funciona",
    what_looking_for: "O Que Procura?",
    services_subtitle: "Explore os nossos serviços abrangentes concebidos para tornar a sua viagem africana inesquecível.",
    accommodation_desc: "De lodges de luxo a pousadas acolhedoras, encontre a sua estadia perfeita em África.",
    rides_transport: "Viagens & Transporte",
    rides_desc: "Veículos de safari, transferências de aeroporto e viagens pela cidade ao seu alcance.",
    event_halls_title: "Salões de Eventos",
    event_halls_desc: "Locais bonitos para casamentos, conferências e celebrações.",
    properties: "Propriedades",
    vehicles: "Veículos",
    venues: "Locais",
    explore: "Explorar",
    testimonials_title: "O Que Dizem Os Nossos Hóspedes",
    testimonials_subtitle: "Não acredite apenas na nossa palavra. Veja o que os viajantes em África dizem.",
    cta_badge: "Para Fornecedores",
    cta_title: "Cresça o Seu Negócio com SafariStay",
    cta_subtitle: "Junte-se a milhares de proprietários, operadores de veículos e gestores de espaços.",
    become_partner: "Torne-se Parceiro",
    partner_login: "Login de Parceiro",
    list_property: "Liste a Sua Propriedade",
    list_property_desc: "Alcance milhares de viajantes em África",
    secure_payments: "Pagamentos Seguros",
    secure_payments_desc: "Receba com segurança e pontualidade",
    support_24_7: "Suporte 24/7",
    support_24_7_desc: "A nossa equipa está sempre aqui para ajudar",
    footer_desc: "A sua plataforma de confiança para alojamento, viagens e salões de eventos em África.",
    services: "Serviços",
    ussd_booking: "Reserva USSD",
    company: "Empresa",
    about_us: "Sobre Nós",
    become_provider: "Torne-se Fornecedor",
    careers: "Carreiras",
    support: "Suporte",
    help_center: "Centro de Ajuda",
    contact_us: "Contacte-Nos",
    privacy_policy: "Política de Privacidade",
    terms_of_service: "Termos de Serviço",
    all_rights_reserved: "Todos os direitos reservados.",
  },
  so: {
    home: "Bogga Hore",
    accommodation: "Hoyga",
    rides: "Raacidda",
    event_halls: "Qolalka Xafladaha",
    how_it_works: "Sida ay u Shaqayso",
    for_providers: "Bixiyeyaasha",
    login: "Soo Gal",
    sign_up: "Is Diiwaan Geli",
    my_profile: "Xogtayda",
    favorites: "Kuwa aan jeclahay",
    my_bookings: "Dalabkayga",
    hero_badge: "Lagu kalsoonaaday 50,000+ socdaaliye",
    hero_title_1: "Baro Afrika",
    hero_title_2: "Jawaaahirta Qarsoon",
    hero_subtitle: "Dalbo hoyga, raacidda, iyo qolalka xafladaha si fudud. Ku raaxayso safar aan dhibaato lahayn oo aad ku samayso web ama USSD.",
    stays: "Hoyga",
    events: "Xafladaha",
    location: "Goobta",
    check_in: "Geli",
    guests: "Martida",
    search: "Raadi",
    book_via_ussd: "Ku dalbo USSD:",
    how_it_works_link: "Sida ay u shaqayso",
    what_looking_for: "Maxaad Raadinaysaa?",
    services_subtitle: "Baro adeegyadeena dhammaystiran ee loo qaabeeyey in ay ka dhigaan safarkaaga Afrika mid aan la illaawin.",
    accommodation_desc: "Laga bilaabo guryaha raaxada ah ilaa guryaha marti-gelinta, raadi hoyga kugu fiican Afrika.",
    rides_transport: "Raacidda & Gaadiidka",
    rides_desc: "Gaadiidka safari, u wareejinta garoonka, iyo raacidda magaalada gacantaada ku jira.",
    event_halls_title: "Qolalka Xafladaha",
    event_halls_desc: "Goobaha quruxda badan ee arooska, shirarka, iyo dabaallaxyada.",
    properties: "Guryaha",
    vehicles: "Gaadiidka",
    venues: "Goobaha",
    explore: "Baro",
    testimonials_title: "Maxay Yidhaahdaan Martidayada",
    testimonials_subtitle: "Ha nooga rumaysan kaliya. Halkan waxaa ku qoran waxa ay yidhaahdaan socdaaliyeyaasha Afrika.",
    cta_badge: "Bixiyeyaasha Adeegga",
    cta_title: "Ku Kor Ganacsigaaga SafariStay",
    cta_subtitle: "Ku biir kumanaan mulkiilayaal, hawlwadeenno gaadiid, iyo maamulayaal goobaha xafladaha.",
    become_partner: "Noqo Lamaane",
    partner_login: "Gelitaanka Lamaanega",
    list_property: "Liis Garee Gurigaaga",
    list_property_desc: "Gaar kumanaan socdaaliye oo Afrika ah",
    secure_payments: "Lacag-bixinno Ammaan ah",
    secure_payments_desc: "Hel lacagtaada si ammaan ah oo waqtiga ku habboon",
    support_24_7: "Taageero 24/7",
    support_24_7_desc: "Kooxdayadu waxay halkan u joogaan inay ku caawiyaan",
    footer_desc: "Madalgaaga la aamino ee hoyga, raacidda, iyo qolalka xafladaha Afrika.",
    services: "Adeegyada",
    ussd_booking: "Dalashada USSD",
    company: "Shirkadda",
    about_us: "Annaga",
    become_provider: "Noqo Bixiye",
    careers: "Shaqooyinka",
    support: "Taageero",
    help_center: "Xarunta Caawinta",
    contact_us: "Nala Soo Xiriir",
    privacy_policy: "Siyaasadda Asturnaanta",
    terms_of_service: "Shuruudaha Adeegga",
    all_rights_reserved: "Dhammaan xuquuqda way dhowran yihiin.",
  },
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState<LanguageCode>(() => {
    const stored = localStorage.getItem("app_language");
    return (stored as LanguageCode) || "en";
  });

  const setLanguage = (lang: LanguageCode) => {
    setLanguageState(lang);
    localStorage.setItem("app_language", lang);
  };

  const t = (key: string): string => {
    return translations[language]?.[key] || translations.en[key] || key;
  };

  useEffect(() => {
    document.documentElement.dir = language === "ar" ? "rtl" : "ltr";
    document.documentElement.lang = language;
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  return useContext(LanguageContext);
};
